[package]
name = "fs_extra"
version = "0.1.0"
description = "Expanding opportunities standard library std::fs and std::io. Recursively copy folders with recept information about process and much more." 
license = "MIT"
authors = ["Denis Kurilenko <webdesus@gmail.com>"]
homepage = "https://github.com/webdesus/fs_extra"
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "CHANGELOG.md",
]

[dependencies]
